### ISSUE TITLE
run mistake

### ISSUE THREAD

**Issue by gitdawn123** [wielandbrendel/adaptive_attacks_paper#2]
hello 
when run the load the base model in 02odds，i met a problem  ：

14 ckpt_dir = 'models/'
     15 ckpt = tf.train.get_checkpoint_state(os.path.join(os.path.expanduser(ckpt_dir), model_name))
---> 16 ckpt_path = ckpt.model_checkpoint_path
     17 saver = tf.train.Saver(var_list=dict((v.name.split('/', 1)[1].split(':')[0], v) for v in tf.global_variables()))
     18 saver.restore(sess, ckpt_path)

AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

how can i fix the problem ？
thank you

**Comment by ftramer** [comment]
The code works fine on my side.
Did you run the `setup.sh`  script to download pre-trained models?
After that you should have a directory `models/naturally_trained` that contains a model checkpoint

**Comment by wsprogrammeryang** [comment]
Thank you for your reply
i run the setup.sh  but it failed to download pre-trained models .
so i download models/naturally_trained from the original website directly，it works.
maybe you can check the script.
thanks a lot.

**Comment by ftramer** [comment]
Can you give more details on how the script fails?
It worked fine on my end.

**Comment by gitdawn123** [comment]
check again ，i found its my mistake. 
my env was lack of   wget , so the script failed.
I apologize for my carelessness and thank you for your  patience.

**Comment by ftramer** [comment]
No worries, thanks for looking into this
