### ISSUE TITLE
Did you try attacking "Asymmetrical Adversarial Training (AAT)" paper with other perturbation types?

### ISSUE THREAD

**Issue by hfeniser** [wielandbrendel/adaptive_attacks_paper#3]
As far as I understand, adversarial training with one perturbation type (e.g. l_inf) can be be weak against attacks of other norms (e.g. l_2). In original AAT paper detectors are trained either with l_inf or l_2 norms (check [here](https://github.com/xuwangyin/GAT-CIFAR10/blob/master/pgd_attack.py#L15) and [here](https://github.com/xuwangyin/GAT-CIFAR10/blob/master/train.py#L18). 
Don't you think this is a weakness? Did you try attacking AAT with l_2 norm version of your PGD ?

**Comment by ftramer** [comment]
We only tried attacks in the l_inf norm. Most of the result in the original paper are for the l_inf norm so we did not try any other attacks
