### ISSUE TITLE
Question about how to design an  adaptive attacks to a new defense ?

### ISSUE THREAD

**Issue by cuge1995** [wielandbrendel/adaptive_attacks_paper#5]
Hey, Wieland Brendel.
We proposed the [IT-Defense](https://github.com/cuge1995/IT-Defense) recently, which utilized the network’s property (such as permutation invariant of input point cloud for Pointnet) to defend attacks. But we don't know how to design an adaptive attack for our defense, could you give any suggestions?

Best wishes!
Jinlai

**Comment by wielandbrendel** [comment]
Your main defence seems to be using (random) input transformations to which the the classifier by design is invariant, right? If that's true, shouldn't an adversarial perturbation that works against one specific permutation also work against all other permutations (given that the response of the classifier is invariant to permutation)?

**Comment by cuge1995** [comment]
Yes, you're right.
Our method can only resist attacks for finding adversarial samples, but the adversarial samples still exist.

**Comment by wielandbrendel** [comment]
But then I am not sure what your attack scenario is? In the standard white-box setting, where you assume your attacker has access to your whole model, your defence wouldn't work. And this setting, at least for me, is basically the only one that truly makes sense from a security point of view.

**Comment by cuge1995** [comment]
We are sorry for the misunderstanding of the standard white-box setting, but we think our method is similar to [1,2], therefore, should we put the input transformation out of the networks?




[1] Chuan Guo, Mayank Rana, Moustapha Cisse, and Laurens Van Der Maaten. “Countering
adversarial images using input transformations”. In: arXiv preprint arXiv:1711.00117 (2017).
[2] Cihang Xie, Jianyu Wang, Zhishuai Zhang, Zhou Ren, and Alan Yuille. “Mitigating adversarial
effects through randomization”. In: arXiv preprint arXiv:1711.01991 (2017).

**Comment by cuge1995** [comment]
After rereading those two papers, I think I know how to choose the right attack scenario. But as suggested in your paper, we should design an adaptive attack for our defense, do you have any suggestions?

**Comment by wielandbrendel** [comment]
The crucial difference is that in [1,2], an adversarial against the network is not necessarily an adversarial after applying the input transformations. If you follow our paper, the right adaptive attack against your defence is to simply attack the original model without the random input transformations.
